disabled_rules:
- todo

line_length: 250

function_body_length: 200

cyclomatic_complexity: 12

excluded: # paths to ignore during linting. Takes precedence over `included`.
- Pods

variable_name:
  excluded: # excluded via string array
    - ok
    - id
    - x
    - y
    - z
    - x0
    - xf
    - y0
    - yf
    - me
    - to
